### ISSUE TITLE
Fails to perform replacement when filename contains underscore.

### ISSUE THREAD

**Issue by estaub** [joeyeng/chunkhash-replace-webpack-plugin#2]
A quick fix would probably be to change

`            .replace(/[^a-z0-9]/gi, ''); // TODO: Make this more rigid
`
to

`            .replace(/[^a-z0-9_]/gi, ''); // TODO: Make this more rigid
`

but you may want to address the issues here more comprehensively.

**Comment by joeyeng** [comment]
Sorry for the late reply. This is fixed now.
