### ISSUE TITLE
Not supporting [contentHash]

### ISSUE THREAD

**Issue by joeweder** [joeyeng/chunkhash-replace-webpack-plugin#3]
If you use [name].[chunkHash].css in the ExtractTextPlugin the resulting JS and CSS have the same chunkHash in their names. This is no good since a change to CSS does not change the CSS filename on a rebuild. The best is to use [name].[contentHash].css, but then your plug-in won't update the CSS <Link/> in my index.html.

**Comment by joeyeng** [comment]
Hi Joe, thanks for the heads up. I was going to add support for this, but given that it deals with content hashes instead of chunkhashes I think making it its own plugin would be a better idea. I'll work on it and update this thread when it's published. Thanks.

**Comment by joeyeng** [comment]
Here's the new plugin: https://www.npmjs.com/package/contenthash-replace-webpack-plugin
